### ISSUE TITLE
Suggestion: Add specs for performance metrics

### ISSUE THREAD

**Issue by mattg42** [stackotter/delta-website#10]
![54A7ED7D-0971-491A-A242-76DA2B7190A4](https://user-images.githubusercontent.com/43332061/166159495-736c266b-5c06-4fe7-aa89-0d0d2b6b18ce.jpeg)
In the * text mention the specs of the device that got those results

**Comment by stackotter** [comment]
Oh whoops, I thought I had done that, good catch. It’s a 2020 dual-core i5 MacBook Air with 8gb ram in case you’re wondering.

**Comment by jxhug** [comment]
fixed in #11
